# SPDX-License-Identifier: BSD-3-Clause
# Copyright(c) 2017 Intel Corporation

include $(RTE_SDK)/mk/rte.vars.mk

DIRS-y += include
DIRS-y += boots
DIRS-y += libzebra
DIRS-y += cmdline
DIRS-y += pid
DIRS-y += itf
DIRS-y += dmr
DIRS-y += acr
DIRS-y += netseg
DIRS-y += dnet
DIRS-y += template
DIRS-y += adp
#DIRS-y += pub
#DIRS-y += url
#DIRS-y += urlr
#DIRS-y += hijack
#DIRS-y += debug
#DIRS-y += ua
#DIRS-y += mask
#DIRS-y += upush
DIRS-y += main

include $(RTE_SDK)/mk/rte.subdir.mk